### ISSUE TITLE
Error after updating to v8

### ISSUE THREAD

**Issue by vtrphan** [popeindustries/inline-source#308]
I got an error like this after updating to v8
`Error: Cannot find module '/.../node_modules/inline-source/index.cjs'`
until now i still use it like const { inlineSource } = require('inline-source');

What must i do to fix this error?

**Comment by popeindustries** [comment]
Sorry, my fault! Should be fixed now in version 8.0.1. Thanks for letting me know
